### ISSUE TITLE
It stopped working unfortunately 😞

### ISSUE THREAD

**Issue by yarub123** [juanborre/alfred-time-anywhere#3]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/84487964/230750870-f0f41e85-11e7-4705-b42b-6a36854fb6ef.png">

**Comment by juanborre** [comment]
Hi @yarub123 ,

Which version are you using?

The [ipgeolocation API](https://ipgeolocation.io/) had a problem with the free API key I'm providing with the workflow and I had to change it recently.

Does it work with the latest version [1.4](https://github.com/juanborre/alfred-time-anywhere/releases/tag/1.4)?

**Comment by yarub123** [comment]
@juanborre Yeah not sure what that was about, at first it gave an Error 404 or 504 I don't quite remember, but it seemed to be something with their servers. Not an issue of your workflow. 

It lasted about a few days, went away, then issue came back. But now it's been working.... in fact it started working after I made this post lol. Sorry about that. 


Confirmed: works on 1.3 as well as 1.4 (which I just tried right now) 🙏

Thanks for following up. 


Edit: yeah, thing is I thought I had my own API as your instructions recommended, but trying to login to their website the other day just wasn't working. Wouldn't let me go past the login page....that was during the time when the service was down and the workflow couldn't fetch. I emailed them, and they had gotten their stuff fixed by the time he replied to me.

**Comment by yarub123** [comment]
@juanborre yup so far last 2 days and today same thing 
<img width="646" alt="image" src="https://user-images.githubusercontent.com/84487964/233522213-35be9e4b-1a41-4b29-a442-523f68278b42.png">

**Comment by juanborre** [comment]
Hmmmm, it seems to be back up now.

It looks like this API has not been stable lately. If these problems keep on happening, I may look into using another source.

**Comment by yarub123** [comment]
No worries yeah it is a bit weird, it's really not a big deal tbh because
it often comes back after a day or two. Cheers.
